name: 🚀 Deploy to cPanel

on:
  push:
    branches:
      - dev # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy via SSH to cPanel
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_KEY }}
          passphrase: ${{ secrets.CPANEL_PASSPHRASE }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            whoami && hostname && pwd
            cd /home/cerasjuo/testingbackend.ceramicandfoodproducts.com
            git pull origin dev
            npm install --legacy-peer-deps
            npm run build

# name: 🚀 Deploy via FTP

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   ftp-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: FTP Deploy
#         uses: SamKirkland/FTP-Deploy-Action@v4
#         with:
#           server: ${{ secrets.FTP_HOST }}
#           username: ${{ secrets.FTP_USER }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           server-dir: /home/cerasjuo/testingbackend.ceramicandfoodproducts.com/
